"""SubprocessRecognizer: real child processes speaking the runner protocol.

Without models: a scripted child (tests/fakes/asr_child_fake.py) started through the same
interpreter (the venv's ``python.exe`` launcher), to check the handshake, tolerant parsing,
watchdogs, error mapping and that a cancel leaves no process behind. With the ``models`` marker:
the real faster-whisper runner on speech generated by ffmpeg's flite filter (the model folder is
``VFE_WHISPER_MODEL_DIR``, default ``<data folder>/models/whisper/large-v3-turbo``).
"""

from __future__ import annotations

import dataclasses
import json
import os
import subprocess
import sys
import threading
import time
from pathlib import Path

import pytest

from vfe_vision.adapters.asr.client import SubprocessRecognizer
from vfe_vision.core.cancel import CancelToken
from vfe_vision.core.config import default_data_dir
from vfe_vision.core.errors import CancelledError, ExternalToolError
from vfe_vision.core.procs import KillOnCloseJob
from vfe_vision.domain.transcript import build_cues, to_srt
from vfe_vision.ports.asr import AsrRequest, GpuFallbackError

FAKE = Path(__file__).parents[1] / "fakes" / "asr_child_fake.py"
REQUEST = AsrRequest(
    audio_path=Path("C:/Rushs été/l'été, [1];x.wav"),
    video_path=None,
    model_dir=Path("C:/modèles/whisper"),
    language=None,
    threads=2,
)


class Recorder:
    def __init__(self) -> None:
        self.calls: list[tuple[float, str | None]] = []

    def __call__(self, fraction: float, message: str | None) -> None:
        self.calls.append((fraction, message))


class Vram:
    """Free video memory read in turn from ``values`` (the last one repeats)."""

    def __init__(self, *values: int | None) -> None:
        self.values = list(values)
        self.reads = 0

    def free_mib(self) -> int | None:
        self.reads += 1
        return self.values.pop(0) if len(self.values) > 1 else self.values[0]


def fake(
    scenario: str,
    pid_file: Path | None = None,
    *,
    stall_timeout_s: float = 180.0,
    timeout_base_s: float = 60.0,
    timeout_per_audio_s: float = 1.0,
    vram: Vram | None = None,
) -> SubprocessRecognizer:
    argv = ["-X", "utf8", str(FAKE), scenario, *([str(pid_file)] if pid_file else [])]
    return SubprocessRecognizer(
        argv=argv,
        stall_timeout_s=stall_timeout_s,
        timeout_base_s=timeout_base_s,
        timeout_per_audio_s=timeout_per_audio_s,
        vram=vram,
        vram_poll_s=0.1,
    )


GPU_REQUEST = dataclasses.replace(REQUEST, device="cuda", cuda_dll_dir=Path("C:/rt/cublas"))


def alive(pid: int) -> bool:
    if sys.platform == "win32":
        import ctypes
        from ctypes import wintypes

        kernel32 = ctypes.WinDLL("kernel32", use_last_error=True)
        kernel32.OpenProcess.restype = wintypes.HANDLE
        kernel32.OpenProcess.argtypes = [wintypes.DWORD, wintypes.BOOL, wintypes.DWORD]
        kernel32.WaitForSingleObject.argtypes = [wintypes.HANDLE, wintypes.DWORD]
        kernel32.WaitForSingleObject.restype = wintypes.DWORD
        kernel32.CloseHandle.argtypes = [wintypes.HANDLE]
        handle = kernel32.OpenProcess(0x00100000 | 0x1000, 0, pid)  # SYNCHRONIZE | QUERY_LIMITED
        if not handle:
            return False
        try:
            return bool(kernel32.WaitForSingleObject(handle, 0) == 0x102)  # WAIT_TIMEOUT: runs
        finally:
            kernel32.CloseHandle(handle)
    else:
        try:
            os.kill(pid, 0)  # no signal: only tells whether the process exists
        except ProcessLookupError:
            return False
        except PermissionError:
            return True
        # A zombie (killed, not yet reaped by its parent) is gone for our purposes.
        done = subprocess.run(
            ["ps", "-o", "stat=", "-p", str(pid)], capture_output=True, text=True, check=False
        )
        state = done.stdout.strip()
        return bool(state) and not state.startswith("Z")


def gone(pid: int, within_s: float = 3.0) -> bool:
    deadline = time.monotonic() + within_s
    while alive(pid):
        if time.monotonic() > deadline:
            return False
        time.sleep(0.05)
    return True


def read_pids(pid_file: Path) -> dict[str, int | None]:
    deadline = time.monotonic() + 10
    while not pid_file.exists():
        assert time.monotonic() < deadline, "the fake child never wrote its pids"
        time.sleep(0.05)
    data: dict[str, int | None] = json.loads(pid_file.read_text(encoding="utf-8"))
    return data


# ---------------------------------------------------------------- protocol
def test_events_become_a_result() -> None:
    progress = Recorder()
    result = fake("ok").transcribe(REQUEST, cancel=CancelToken(), progress=progress)

    assert result.status == "ok"
    assert (result.language, result.language_probability) == ("fr", 0.97)
    assert [(lang.code, lang.probability) for lang in result.languages] == [
        ("fr", 0.97),
        ("en", 0.02),
    ]
    assert (result.duration_s, result.speech_s, result.model) == (10.0, 7.5, "fake/whisper")
    # Second-pass segments are merged in time order and renumbered.
    assert [s.start for s in result.segments] == [0.5, 3.2, 6.0]
    assert [s.idx for s in result.segments] == [0, 1, 2]
    assert [s.second_pass for s in result.segments] == [False, True, False]
    assert [s.suspect for s in result.segments] == [False, False, True]
    assert result.segments[0].words[0].text == " Bonjour"
    assert result.text == "Bonjour à tous ou un petit oiseau"
    # Stray and malformed lines are tolerated and counted, not fatal.
    assert result.stats["stray_lines"] == 5
    assert isinstance(result.stats["child_pid"], int)
    # The request crossed stdin intact (accents, apostrophe, brackets, no command line).
    sent = result.stats["request"]
    assert sent["audio_path"] == str(REQUEST.audio_path)
    assert sent["model_dir"] == str(REQUEST.model_dir)
    assert sent["threads"] == 2
    assert sent["video_path"] is None

    fractions = [f for f, _ in progress.calls]
    assert fractions == sorted(fractions)
    assert len(set(progress.calls)) == len(progress.calls)  # no duplicate notification
    assert fractions[-1] == 1.0
    assert all(0.0 <= f <= 1.0 for f in fractions)
    messages = [m for _, m in progress.calls if m]
    assert "Chargement du modèle de transcription" in messages
    assert "Seconde passe sur la parole manquée" in messages
    assert messages[-1] == "Transcription terminée"
    assert (0.10 + 0.90 * 0.3, "Transcription") in progress.calls


def test_a_cpu_request_hides_the_gpu() -> None:
    result = fake("ok").transcribe(REQUEST, cancel=CancelToken(), progress=Recorder())
    assert result.stats["request"]["device"] == "cpu"
    assert "vram_min_free_mib" not in result.stats


# ---------------------------------------------------------------- GPU
def test_a_gpu_run_starts_after_the_memory_check() -> None:
    vram = Vram(3000)
    result = fake("gpu_ok", vram=vram).transcribe(
        GPU_REQUEST, cancel=CancelToken(), progress=Recorder()
    )
    assert result.stats["device"] == "cuda"
    assert result.stats["visible"] == "0"  # the parent exposes GPU 0 to this child only
    assert result.stats["order"] == "PCI_BUS_ID"  # the card nvidia-smi calls 0
    assert result.stats["allocator"] == "cuda_malloc_async"
    assert result.stats["cuda_dll_dir"] == str(Path("C:/rt/cublas"))
    assert result.stats["vram_min_free_mib"] == 3000
    assert vram.reads >= 1


def test_short_of_memory_once_loaded_gives_the_file_back_to_the_cpu() -> None:
    with pytest.raises(GpuFallbackError) as caught:
        fake("gpu_ok", vram=Vram(700)).transcribe(
            GPU_REQUEST, cancel=CancelToken(), progress=Recorder()
        )
    assert "700 Mio" in caught.value.reason
    assert not caught.value.disable  # only short this time


def test_unknown_memory_is_never_a_go() -> None:
    with pytest.raises(GpuFallbackError):
        fake("gpu_ok", vram=Vram(None)).transcribe(
            GPU_REQUEST, cancel=CancelToken(), progress=Recorder()
        )
    with pytest.raises(GpuFallbackError) as caught:
        fake("gpu_ok").transcribe(GPU_REQUEST, cancel=CancelToken(), progress=Recorder())
    assert caught.value.disable  # no probe at all: never try again


def test_the_lending_rule_is_checked_again_before_cuda_starts() -> None:
    request = dataclasses.replace(GPU_REQUEST, gpu_min_free_mib=2688)  # turbo: need + margin
    with pytest.raises(GpuFallbackError, match="avant le chargement"):
        fake("gpu_ok", vram=Vram(2000)).transcribe(
            request, cancel=CancelToken(), progress=Recorder()
        )
    result = fake("gpu_ok", vram=Vram(2700)).transcribe(
        request, cancel=CancelToken(), progress=Recorder()
    )
    assert result.stats["device"] == "cuda"


def test_an_audio_error_is_not_a_gpu_problem() -> None:
    with pytest.raises(ExternalToolError, match="AudioDecodeError"):
        fake("gpu_bad_audio", vram=Vram(3000)).transcribe(
            GPU_REQUEST, cancel=CancelToken(), progress=Recorder()
        )


def test_a_load_that_never_ends_gives_the_gpu_back(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    from vfe_vision.adapters.asr import client

    monkeypatch.setattr(client, "LOAD_TIMEOUT_S", 1.0)
    pid_file = tmp_path / "pids.json"
    with pytest.raises(GpuFallbackError, match="ne s'est pas chargé"):
        fake("gpu_slow_load", pid_file, vram=Vram(3000)).transcribe(
            GPU_REQUEST, cancel=CancelToken(), progress=Recorder()
        )
    pid = read_pids(pid_file)["pid"]
    assert pid is not None
    assert gone(pid)


def test_the_warm_check_keeps_room_for_decoding() -> None:
    request = dataclasses.replace(GPU_REQUEST, gpu_headroom_mib=384)  # needs 512 + 384 free
    result = fake("gpu_ok", vram=Vram(900)).transcribe(
        request, cancel=CancelToken(), progress=Recorder()
    )
    assert result.stats["device"] == "cuda"
    with pytest.raises(GpuFallbackError, match="896 nécessaires"):
        fake("gpu_ok", vram=Vram(850)).transcribe(
            request, cancel=CancelToken(), progress=Recorder()
        )


def test_memory_is_watched_while_the_model_loads(tmp_path: Path) -> None:
    pid_file = tmp_path / "pids.json"
    started = time.monotonic()
    with pytest.raises(GpuFallbackError, match="300 Mio"):
        fake("gpu_slow_load", pid_file, vram=Vram(3000, 300)).transcribe(
            GPU_REQUEST, cancel=CancelToken(), progress=Recorder()
        )
    assert time.monotonic() - started < 10  # not after the 30 s load
    pid = read_pids(pid_file)["pid"]
    assert pid is not None
    assert gone(pid)


def test_memory_falling_during_the_run_stops_the_child(tmp_path: Path) -> None:
    pid_file = tmp_path / "pids.json"
    started = time.monotonic()
    with pytest.raises(GpuFallbackError) as caught:
        fake("gpu_long", pid_file, vram=Vram(3000, 3000, 2000, 400)).transcribe(
            GPU_REQUEST, cancel=CancelToken(), progress=Recorder()
        )
    assert "400 Mio" in caught.value.reason
    assert time.monotonic() - started < 15
    pid = read_pids(pid_file)["pid"]
    assert pid is not None
    assert gone(pid)


def test_cuda_that_does_not_load_is_not_tried_again() -> None:
    with pytest.raises(GpuFallbackError) as caught:
        fake("gpu_unavailable", vram=Vram(3000)).transcribe(
            GPU_REQUEST, cancel=CancelToken(), progress=Recorder()
        )
    assert caught.value.disable
    assert "cublas64_12" in caught.value.reason


def test_a_gpu_crash_is_redone_on_the_cpu() -> None:
    with pytest.raises(GpuFallbackError) as caught:
        fake("gpu_crash", vram=Vram(3000)).transcribe(
            GPU_REQUEST, cancel=CancelToken(), progress=Recorder()
        )
    assert not caught.value.disable


def test_no_speech() -> None:
    progress = Recorder()
    result = fake("no_speech").transcribe(REQUEST, cancel=CancelToken(), progress=progress)
    assert result.status == "no_speech"
    assert result.language is None
    assert result.language_probability is None
    assert result.segments == ()
    assert result.speech_s == 0.2
    assert progress.calls[-1] == (1.0, "Aucune parole détectée")


# ---------------------------------------------------------------- failures
def test_stall_timeout_kills_the_whole_tree(tmp_path: Path) -> None:
    pid_file = tmp_path / "pids.json"
    started = time.monotonic()
    with pytest.raises(ExternalToolError, match="ne répond plus"):
        fake("hang", pid_file, stall_timeout_s=1.5).transcribe(
            REQUEST, cancel=CancelToken(), progress=Recorder()
        )
    assert time.monotonic() - started < 15
    pids = read_pids(pid_file)
    assert pids["pid"] is not None
    assert gone(pids["pid"])
    assert pids["grandchild"] is not None
    assert gone(pids["grandchild"])


def test_a_silent_child_that_keeps_computing_is_not_killed(monkeypatch: pytest.MonkeyPatch) -> None:
    # A low-priority child slowed down by other work is silent but uses CPU: kept (the job
    # counts the CPU time of the whole tree: Job Object accounting, or ``ps`` on POSIX).
    monkeypatch.setattr("vfe_vision.adapters.asr.client.STALL_MIN_CPU_S", 0.5)
    result = fake("busy", stall_timeout_s=1.5).transcribe(
        REQUEST, cancel=CancelToken(), progress=Recorder()
    )
    assert result.status == "no_speech"


def test_a_child_that_never_says_hello_is_stopped(tmp_path: Path) -> None:
    pid_file = tmp_path / "pids.json"
    with pytest.raises(ExternalToolError, match="ne répond plus"):
        fake("mute", pid_file, stall_timeout_s=1.5).transcribe(
            REQUEST, cancel=CancelToken(), progress=Recorder()
        )
    pid = read_pids(pid_file)["pid"]
    assert pid is not None
    assert gone(pid)


def test_exit_code_and_stderr_tail() -> None:
    with pytest.raises(ExternalToolError, match=r"code 3.*boom in the child") as caught:
        fake("exit3").transcribe(REQUEST, cancel=CancelToken(), progress=Recorder())
    assert caught.value.extra["returncode"] == 3


def test_dll_load_failed_gets_the_smart_app_control_hint() -> None:
    with pytest.raises(ExternalToolError, match="Smart App Control") as caught:
        fake("dll").transcribe(REQUEST, cancel=CancelToken(), progress=Recorder())
    assert "ImportError" in caught.value.detail
    assert caught.value.extra["hint"]


def test_child_error_is_reported() -> None:
    with pytest.raises(ExternalToolError, match="aucune piste audio") as caught:
        fake("error").transcribe(REQUEST, cancel=CancelToken(), progress=Recorder())
    assert "NoAudioStream" in caught.value.detail
    assert caught.value.extra["hint"] is None


def test_exit_zero_without_done_is_a_failure() -> None:
    # A child killed by its Job Object exits with code 0: only 'done' means success.
    with pytest.raises(ExternalToolError, match="sans terminer"):
        fake("no_done").transcribe(REQUEST, cancel=CancelToken(), progress=Recorder())


def test_global_deadline(tmp_path: Path) -> None:
    pid_file = tmp_path / "pids.json"
    recognizer = fake("slow", pid_file, timeout_base_s=1.0, timeout_per_audio_s=0.0)
    with pytest.raises(ExternalToolError, match="durée maximale"):
        recognizer.transcribe(REQUEST, cancel=CancelToken(), progress=Recorder())
    pids = read_pids(pid_file)
    assert pids["pid"] is not None
    assert gone(pids["pid"])


def test_missing_interpreter() -> None:
    recognizer = SubprocessRecognizer(python=str(Path(sys.executable).with_name("absent.exe")))
    with pytest.raises(ExternalToolError, match="Impossible de lancer"):
        recognizer.transcribe(REQUEST, cancel=CancelToken(), progress=Recorder())


# ---------------------------------------------------------------- cancellation
def test_cancel_mid_run_leaves_no_process(tmp_path: Path) -> None:
    pid_file = tmp_path / "pids.json"
    cancel = CancelToken()
    progress = Recorder()

    def cancel_when_running() -> None:
        read_pids(pid_file)
        time.sleep(0.5)
        cancel.cancel("Annulé par le test")

    threading.Thread(target=cancel_when_running, daemon=True).start()
    with pytest.raises(CancelledError, match="Annulé par le test"):
        fake("slow", pid_file).transcribe(REQUEST, cancel=cancel, progress=progress)
    pids = read_pids(pid_file)
    assert pids["pid"] is not None
    assert gone(pids["pid"], within_s=2.0)
    assert pids["grandchild"] is not None
    assert gone(pids["grandchild"], within_s=2.0)
    assert progress.calls  # it was running


def test_cancelled_before_start_spawns_nothing() -> None:
    cancel = CancelToken()
    cancel.cancel()
    with pytest.raises(CancelledError):
        fake("ok").transcribe(REQUEST, cancel=cancel, progress=Recorder())


def test_job_catches_the_real_interpreter_behind_the_launcher() -> None:
    """Windows: the venv's ``python.exe`` is a launcher whose child is the real interpreter;
    POSIX: ``python`` is the interpreter itself, in its own process group."""
    code = "import os, sys, time; print(os.getpid(), flush=True); time.sleep(60)"
    job = KillOnCloseJob()
    proc = subprocess.Popen(
        [sys.executable, "-c", code],
        stdout=subprocess.PIPE,
        stdin=subprocess.DEVNULL,
        **job.popen_kwargs(),
    )
    try:
        job.assign(proc)
        assert proc.stdout is not None
        real = int(proc.stdout.readline())
        assert job.ensure_pid(real)
        assert job.contains(real) is True
        assert job.contains(os.getpid()) is False
    finally:
        job.close()
        proc.wait(10)
        if proc.stdout is not None:
            proc.stdout.close()
    assert gone(real)
    assert job.contains(real) is None  # closed job: cannot tell


# ---------------------------------------------------------------- real model
def _model_dir() -> Path:
    configured = os.environ.get("VFE_WHISPER_MODEL_DIR")
    if configured:
        return Path(configured)
    return default_data_dir() / "models" / "whisper" / "large-v3-turbo"


def _has_flite() -> bool:
    try:
        filters = subprocess.run(
            ["ffmpeg", "-hide_banner", "-filters"], capture_output=True, check=False, timeout=30
        ).stdout.decode("utf-8", errors="replace")
    except (OSError, subprocess.TimeoutExpired):
        return False
    return any(line.split()[1:2] == ["flite"] for line in filters.splitlines())


SPEECH = "Hello everyone. Today we are cooking rice in a small kitchen. The weather is sunny."


@pytest.fixture(scope="module")
def model_dir() -> Path:
    folder = _model_dir()
    if not (folder / "model.bin").is_file():
        pytest.skip(f"modèle Whisper absent : {folder}")
    return folder


@pytest.fixture(scope="module")
def speech_wav(tmp_path_factory: pytest.TempPathFactory) -> Path:
    if not _has_flite():
        pytest.skip("ffmpeg sans le filtre flite")
    target = tmp_path_factory.mktemp("asr") / "speech.wav"
    subprocess.run(
        [
            "ffmpeg", "-v", "error", "-y", "-f", "lavfi", "-i", f"flite=text='{SPEECH}':voice=slt",
            "-af", "apad=pad_dur=1", "-ar", "16000", "-ac", "1", "-c:a", "pcm_s16le", str(target),
        ],
        check=True,
    )  # fmt: skip
    return target


def _request(
    model_dir: Path, *, audio_path: Path | None = None, video_path: Path | None = None
) -> AsrRequest:
    return AsrRequest(
        audio_path=audio_path, video_path=video_path, model_dir=model_dir, language=None, threads=4
    )


@pytest.mark.models
def test_real_transcription_of_generated_speech(model_dir: Path, speech_wav: Path) -> None:
    progress = Recorder()
    result = SubprocessRecognizer().transcribe(
        _request(model_dir, audio_path=speech_wav), cancel=CancelToken(), progress=progress
    )
    assert result.status == "ok"
    assert result.language == "en"
    assert "rice" in result.text.lower()
    assert result.segments
    assert all(s.words for s in result.segments)
    assert all(0.0 <= w.start <= w.end <= result.duration_s + 0.5
               for s in result.segments for w in s.words)  # fmt: skip
    assert "load_s" in result.stats
    assert progress.calls[-1] == (1.0, "Transcription terminée")
    assert to_srt(build_cues(result.segments)).startswith("1\n00:00:0")


@pytest.mark.models
def test_the_child_decodes_a_video(model_dir: Path, speech_wav: Path, tmp_path: Path) -> None:
    video = tmp_path / "plan séquence.mp4"
    subprocess.run(
        [
            "ffmpeg", "-v", "error", "-y", "-f", "lavfi", "-i", "color=c=gray:s=160x120:r=10",
            "-i", str(speech_wav), "-map", "0:v", "-map", "1:a", "-shortest",
            "-c:v", "libx264", "-pix_fmt", "yuv420p", "-c:a", "aac", str(video),
        ],
        check=True,
    )  # fmt: skip
    result = SubprocessRecognizer().transcribe(
        _request(model_dir, video_path=video), cancel=CancelToken(), progress=Recorder()
    )
    assert result.status == "ok"
    assert "rice" in result.text.lower()


@pytest.mark.models
def test_silence_never_loads_the_model(model_dir: Path, tmp_path: Path) -> None:
    silence = tmp_path / "silence.wav"
    subprocess.run(
        ["ffmpeg", "-v", "error", "-y", "-f", "lavfi", "-i", "anullsrc=r=16000:cl=mono",
         "-t", "4", "-c:a", "pcm_s16le", str(silence)],
        check=True,
    )  # fmt: skip
    result = SubprocessRecognizer().transcribe(
        _request(model_dir, audio_path=silence), cancel=CancelToken(), progress=Recorder()
    )
    assert result.status == "no_speech"
    assert result.language is None
    assert "load_s" not in result.stats
