"""initial schema

Revision ID: 0001
Revises:
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("job_id", sa.String(length=32), nullable=True),
        sa.Column("video_id", sa.String(length=32), nullable=True),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
    )
    op.create_table(
        "library_roots",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("path_key", sa.Text(), nullable=False),
        sa.Column("volume_serial", sa.String(length=32), nullable=True),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("recursive", sa.Boolean(), nullable=False),
        sa.Column("exclude_globs", sa.JSON(), nullable=False),
        sa.Column("analysis_focus", sa.Text(), nullable=True),
        sa.Column("clock_offset_s", sa.Integer(), nullable=True),
        sa.Column("default_latitude", sa.Double(), nullable=True),
        sa.Column("default_longitude", sa.Double(), nullable=True),
        sa.Column("default_timezone", sa.String(length=64), nullable=True),
        sa.Column("auto_analyze", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_scan_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_library_roots")),
        sa.UniqueConstraint("path_key", name=op.f("uq_library_roots_path_key")),
    )
    op.create_table(
        "llm_calls",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("cache_key", sa.String(length=64), nullable=False),
        sa.Column("purpose", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("prompt_version", sa.String(length=32), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("response", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_calls")),
        sa.UniqueConstraint("cache_key", name=op.f("uq_llm_calls_cache_key")),
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_settings")),
    )
    op.create_table(
        "videos",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("root_id", sa.String(length=32), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("path_key", sa.Text(), nullable=False),
        sa.Column("rel_path", sa.Text(), nullable=False),
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("mtime", sa.Double(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "new",
                "queued",
                "analyzing",
                "ready",
                "partial",
                "failed",
                "offline",
                name="videostatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("duration_s", sa.Double(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("fps", sa.Double(), nullable=True),
        sa.Column("video_codec", sa.String(length=32), nullable=True),
        sa.Column("audio_codec", sa.String(length=32), nullable=True),
        sa.Column("has_audio", sa.Boolean(), nullable=True),
        sa.Column(
            "orientation",
            sa.Enum(
                "horizontal", "vertical", "square", name="orientation", native_enum=False, length=32
            ),
            nullable=True,
        ),
        sa.Column("is_hdr", sa.Boolean(), nullable=True),
        sa.Column("color_transfer", sa.String(length=32), nullable=True),
        sa.Column("start_timecode", sa.String(length=16), nullable=True),
        sa.Column("encoder", sa.String(length=200), nullable=True),
        sa.Column("captured_at", sa.DateTime(), nullable=True),
        sa.Column("captured_at_source", sa.String(length=64), nullable=True),
        sa.Column("captured_at_confidence", sa.String(length=16), nullable=True),
        sa.Column("capture_timezone", sa.String(length=64), nullable=True),
        sa.Column("latitude", sa.Double(), nullable=True),
        sa.Column("longitude", sa.Double(), nullable=True),
        sa.Column("altitude_m", sa.Double(), nullable=True),
        sa.Column("location_source", sa.String(length=64), nullable=True),
        sa.Column("camera_make", sa.String(length=100), nullable=True),
        sa.Column("camera_model", sa.String(length=100), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("poster_path", sa.Text(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("favorite", sa.Boolean(), nullable=False),
        sa.Column("user_notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("last_analyzed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["root_id"],
            ["library_roots.id"],
            name=op.f("fk_videos_root_id_library_roots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_videos")),
        sa.UniqueConstraint("path_key", name=op.f("uq_videos_path_key")),
    )
    with op.batch_alter_table("videos", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_videos_fingerprint"), ["fingerprint"], unique=False)
        batch_op.create_index(batch_op.f("ix_videos_root_id"), ["root_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_videos_status"), ["status"], unique=False)

    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("analyze_video", "scan_root", name="jobkind", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("video_id", sa.String(length=32), nullable=True),
        sa.Column("root_id", sa.String(length=32), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "succeeded",
                "partial",
                "failed",
                "cancelled",
                name="jobstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("progress", sa.Double(), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("worker_pid", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["root_id"],
            ["library_roots.id"],
            name=op.f("fk_jobs_root_id_library_roots"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["video_id"], ["videos.id"], name=op.f("fk_jobs_video_id_videos"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_jobs_status_priority", ["status", "priority", "created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_jobs_video_id"), ["video_id"], unique=False)

    op.create_table(
        "keyframes",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("video_id", sa.String(length=32), nullable=False),
        sa.Column("idx", sa.Integer(), nullable=False),
        sa.Column("t_s", sa.Double(), nullable=False),
        sa.Column("image_path", sa.Text(), nullable=False),
        sa.Column("thumb_path", sa.Text(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("selection_reason", sa.String(length=32), nullable=False),
        sa.Column("phash", sa.String(length=16), nullable=True),
        sa.Column("duplicate_of", sa.String(length=32), nullable=True),
        sa.Column("sharpness", sa.Double(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
            name=op.f("fk_keyframes_video_id_videos"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_keyframes")),
        sa.UniqueConstraint("video_id", "idx", name=op.f("uq_keyframes_video_id")),
    )
    with op.batch_alter_table("keyframes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_keyframes_video_id"), ["video_id"], unique=False)

    op.create_table(
        "video_metadata",
        sa.Column("video_id", sa.String(length=32), nullable=False),
        sa.Column("probe", sa.JSON(), nullable=True),
        sa.Column("exif", sa.JSON(), nullable=True),
        sa.Column("normalized", sa.JSON(), nullable=True),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
            name=op.f("fk_video_metadata_video_id_videos"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("video_id", name=op.f("pk_video_metadata")),
    )
    op.create_table(
        "frame_analyses",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("keyframe_id", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("prompt_version", sa.String(length=32), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("focus", sa.Text(), nullable=True),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["keyframe_id"],
            ["keyframes.id"],
            name=op.f("fk_frame_analyses_keyframe_id_keyframes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_frame_analyses")),
        sa.UniqueConstraint("keyframe_id", name=op.f("uq_frame_analyses_keyframe_id")),
    )
    op.create_table(
        "stage_runs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("job_id", sa.String(length=32), nullable=True),
        sa.Column("video_id", sa.String(length=32), nullable=False),
        sa.Column("stage", sa.String(length=64), nullable=False),
        sa.Column("stage_version", sa.Integer(), nullable=False),
        sa.Column("cache_key", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "succeeded",
                "cached",
                "skipped",
                "failed",
                "cancelled",
                name="stagestatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("skip_reason", sa.Text(), nullable=True),
        sa.Column("summary", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_stage_runs_job_id_jobs"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
            name=op.f("fk_stage_runs_video_id_videos"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stage_runs")),
    )
    with op.batch_alter_table("stage_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_stage_runs_job_id"), ["job_id"], unique=False)
        batch_op.create_index(
            "ix_stage_runs_video_stage", ["video_id", "stage", "created_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stage_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_stage_runs_video_stage")
        batch_op.drop_index(batch_op.f("ix_stage_runs_job_id"))

    op.drop_table("stage_runs")
    op.drop_table("frame_analyses")
    op.drop_table("video_metadata")
    with op.batch_alter_table("keyframes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_keyframes_video_id"))

    op.drop_table("keyframes")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_jobs_video_id"))
        batch_op.drop_index("ix_jobs_status_priority")

    op.drop_table("jobs")
    with op.batch_alter_table("videos", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_videos_status"))
        batch_op.drop_index(batch_op.f("ix_videos_root_id"))
        batch_op.drop_index(batch_op.f("ix_videos_fingerprint"))

    op.drop_table("videos")
    op.drop_table("settings")
    op.drop_table("llm_calls")
    op.drop_table("library_roots")
    op.drop_table("events")
    # ### end Alembic commands ###
