"""media metadata shots signals

Revision ID: 0002
Revises: 0001
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audio_stats",
        sa.Column("video_id", sa.String(length=32), nullable=False),
        sa.Column("integrated_lufs", sa.Double(), nullable=True),
        sa.Column("loudness_range_lu", sa.Double(), nullable=True),
        sa.Column("true_peak_dbfs", sa.Double(), nullable=True),
        sa.Column("silence_ratio", sa.Double(), nullable=True),
        sa.Column("silences", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
            name=op.f("fk_audio_stats_video_id_videos"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("video_id", name=op.f("pk_audio_stats")),
    )
    op.create_table(
        "gps_points",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("video_id", sa.String(length=32), nullable=False),
        sa.Column("t_s", sa.Double(), nullable=True),
        sa.Column("utc", sa.DateTime(), nullable=True),
        sa.Column("latitude", sa.Double(), nullable=False),
        sa.Column("longitude", sa.Double(), nullable=False),
        sa.Column("altitude_m", sa.Double(), nullable=True),
        sa.Column("speed_mps", sa.Double(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
            name=op.f("fk_gps_points_video_id_videos"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gps_points")),
    )
    with op.batch_alter_table("gps_points", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_gps_points_video_id"), ["video_id"], unique=False)

    op.create_table(
        "shots",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("video_id", sa.String(length=32), nullable=False),
        sa.Column("idx", sa.Integer(), nullable=False),
        sa.Column("start_s", sa.Double(), nullable=False),
        sa.Column("end_s", sa.Double(), nullable=False),
        sa.Column("boundary", sa.String(length=16), nullable=False),
        sa.Column("motion", sa.String(length=16), nullable=False),
        sa.Column("motion_score", sa.Double(), nullable=False),
        sa.Column("stability", sa.Double(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["video_id"], ["videos.id"], name=op.f("fk_shots_video_id_videos"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shots")),
        sa.UniqueConstraint("video_id", "idx", name=op.f("uq_shots_video_id")),
    )
    with op.batch_alter_table("shots", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_shots_video_id"), ["video_id"], unique=False)

    op.create_table(
        "video_signals",
        sa.Column("video_id", sa.String(length=32), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("visual", sa.JSON(), nullable=True),
        sa.Column("audio", sa.JSON(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
            name=op.f("fk_video_signals_video_id_videos"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("video_id", name=op.f("pk_video_signals")),
    )
    with op.batch_alter_table("keyframes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("shot_id", sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column("metrics", sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f("ix_keyframes_shot_id"), ["shot_id"], unique=False)
        batch_op.create_foreign_key(
            batch_op.f("fk_keyframes_shot_id_shots"),
            "shots",
            ["shot_id"],
            ["id"],
            ondelete="SET NULL",
        )

    with op.batch_alter_table("videos", schema=None) as batch_op:
        batch_op.add_column(sa.Column("color_profile", sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("videos", schema=None) as batch_op:
        batch_op.drop_column("color_profile")

    with op.batch_alter_table("keyframes", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_keyframes_shot_id_shots"), type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_keyframes_shot_id"))
        batch_op.drop_column("metrics")
        batch_op.drop_column("shot_id")

    op.drop_table("video_signals")
    with op.batch_alter_table("shots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_shots_video_id"))

    op.drop_table("shots")
    with op.batch_alter_table("gps_points", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_gps_points_video_id"))

    op.drop_table("gps_points")
    op.drop_table("audio_stats")
    # ### end Alembic commands ###
