"""French names of the 527 AudioSet sound classes (YAMNet and CED display names are English).

Written for a list of sounds heard in holiday footage: short noun phrases, plural for repeated
animal or human sounds (« Aboiements », « Rires »). « Snake » is named after what it catches on
rushes (a sharp hiss), never « Serpent ». Keys are the exact AudioSet ``display_name`` values.
"""

from __future__ import annotations

from collections.abc import Mapping


def sound_name(label: str, language: str = "fr") -> str:
    """Display name of an AudioSet class in ``language`` (the English name otherwise)."""
    if language == "fr":
        return FRENCH.get(label, label)
    return label


FRENCH: Mapping[str, str] = {
    "Speech": "Parole",
    "Male speech, man speaking": "Voix d'homme",
    "Female speech, woman speaking": "Voix de femme",
    "Child speech, kid speaking": "Voix d'enfant",
    "Conversation": "Conversation",
    "Narration, monologue": "Narration",
    "Babbling": "Babillage",
    "Speech synthesizer": "Voix de synthèse",
    "Shout": "Cris",
    "Bellow": "Braillements",
    "Whoop": "Cri de joie",
    "Yell": "Vociférations",
    "Battle cry": "Cri de guerre",
    "Children shouting": "Cris d'enfants",
    "Screaming": "Cris perçants",
    "Whispering": "Chuchotements",
    "Laughter": "Rires",
    "Baby laughter": "Rires de bébé",
    "Giggle": "Gloussements",
    "Snicker": "Ricanements",
    "Belly laugh": "Éclats de rire",
    "Chuckle, chortle": "Petits rires",
    "Crying, sobbing": "Pleurs",
    "Baby cry, infant cry": "Pleurs de bébé",
    "Whimper": "Geignements",
    "Wail, moan": "Lamentations",
    "Sigh": "Soupir",
    "Singing": "Chant",
    "Choir": "Chœur",
    "Yodeling": "Yodel",
    "Chant": "Psalmodie",
    "Mantra": "Mantra",
    "Male singing": "Chant masculin",
    "Female singing": "Chant féminin",
    "Child singing": "Chant d'enfant",
    "Synthetic singing": "Chant synthétique",
    "Rapping": "Rap",
    "Humming": "Fredonnement",
    "Groan": "Gémissements",
    "Grunt": "Grognement (humain)",
    "Whistling": "Sifflement",
    "Breathing": "Respiration",
    "Wheeze": "Respiration sifflante",
    "Snoring": "Ronflement",
    "Gasp": "Inspiration brusque",
    "Pant": "Halètement",
    "Snort": "Souffle nasal",
    "Cough": "Toux",
    "Throat clearing": "Raclement de gorge",
    "Sneeze": "Éternuement",
    "Sniff": "Reniflement",
    "Run": "Pas de course",
    "Shuffle": "Pas traînants",
    "Walk, footsteps": "Pas",
    "Chewing, mastication": "Mastication",
    "Biting": "Morsure",
    "Gargling": "Gargarisme",
    "Stomach rumble": "Gargouillis d'estomac",
    "Burping, eructation": "Rot",
    "Hiccup": "Hoquet",
    "Fart": "Pet",
    "Hands": "Bruits de mains",
    "Finger snapping": "Claquement de doigts",
    "Clapping": "Battements de mains",
    "Heart sounds, heartbeat": "Battements de cœur",
    "Heart murmur": "Souffle cardiaque",
    "Cheering": "Acclamations",
    "Applause": "Applaudissements",
    "Chatter": "Bavardage",
    "Crowd": "Foule",
    "Hubbub, speech noise, speech babble": "Brouhaha",
    "Children playing": "Enfants qui jouent",
    "Animal": "Animal",
    "Domestic animals, pets": "Animaux domestiques",
    "Dog": "Chien",
    "Bark": "Aboiements",
    "Yip": "Jappements",
    "Howl": "Hurlement",
    "Bow-wow": "Ouaf-ouaf",
    "Growling": "Grognement",
    "Whimper (dog)": "Gémissements de chien",
    "Cat": "Chat",
    "Purr": "Ronronnement",
    "Meow": "Miaulements",
    "Hiss": "Sifflement (souffle)",
    "Caterwaul": "Miaulements stridents",
    "Livestock, farm animals, working animals": "Animaux de ferme",
    "Horse": "Cheval",
    "Clip-clop": "Sabots (pas de cheval)",
    "Neigh, whinny": "Hennissement",
    "Cattle, bovinae": "Vaches",
    "Moo": "Meuglement",
    "Cowbell": "Cloche de vache",
    "Pig": "Cochon",
    "Oink": "Grognement de cochon",
    "Goat": "Chèvre",
    "Bleat": "Bêlement",
    "Sheep": "Mouton",
    "Fowl": "Volaille",
    "Chicken, rooster": "Poule, coq",
    "Cluck": "Caquètement",
    "Crowing, cock-a-doodle-doo": "Chant du coq",
    "Turkey": "Dindon",
    "Gobble": "Glouglou du dindon",
    "Duck": "Canard",
    "Quack": "Cancanement",
    "Goose": "Oie",
    "Honk": "Cri d'oie",
    "Wild animals": "Animaux sauvages",
    "Roaring cats (lions, tigers)": "Grands félins",
    "Roar": "Rugissement",
    "Bird": "Oiseau",
    "Bird vocalization, bird call, bird song": "Chant d'oiseau",
    "Chirp, tweet": "Pépiements",
    "Squawk": "Criaillement",
    "Pigeon, dove": "Pigeon, tourterelle",
    "Coo": "Roucoulement",
    "Crow": "Corneille",
    "Caw": "Croassement",
    "Owl": "Chouette, hibou",
    "Hoot": "Hululement",
    "Bird flight, flapping wings": "Battements d'ailes",
    "Canidae, dogs, wolves": "Canidés",
    "Rodents, rats, mice": "Rongeurs",
    "Mouse": "Souris",
    "Patter": "Trottinement",
    "Insect": "Insecte",
    "Cricket": "Grillon",
    "Mosquito": "Moustique",
    "Fly, housefly": "Mouche",
    "Buzz": "Bourdonnement",
    "Bee, wasp, etc.": "Abeille, guêpe",
    "Frog": "Grenouille",
    "Croak": "Coassement",
    "Snake": "Sifflement aigu",
    "Rattle": "Cliquetis",
    "Whale vocalization": "Chant de baleine",
    "Music": "Musique",
    "Musical instrument": "Instrument",
    "Plucked string instrument": "Cordes pincées",
    "Guitar": "Guitare",
    "Electric guitar": "Guitare électrique",
    "Bass guitar": "Guitare basse",
    "Acoustic guitar": "Guitare acoustique",
    "Steel guitar, slide guitar": "Guitare hawaïenne",
    "Tapping (guitar technique)": "Tapping (guitare)",
    "Strum": "Accords grattés",
    "Banjo": "Banjo",
    "Sitar": "Sitar",
    "Mandolin": "Mandoline",
    "Zither": "Cithare",
    "Ukulele": "Ukulélé",
    "Keyboard (musical)": "Clavier (musique)",
    "Piano": "Piano",
    "Electric piano": "Piano électrique",
    "Organ": "Orgue",
    "Electronic organ": "Orgue électronique",
    "Hammond organ": "Orgue Hammond",
    "Synthesizer": "Synthétiseur",
    "Sampler": "Échantillonneur",
    "Harpsichord": "Clavecin",
    "Percussion": "Percussions",
    "Drum kit": "Batterie",
    "Drum machine": "Boîte à rythmes",
    "Drum": "Tambour",
    "Snare drum": "Caisse claire",
    "Rimshot": "Rimshot",
    "Drum roll": "Roulement de tambour",
    "Bass drum": "Grosse caisse",
    "Timpani": "Timbales",
    "Tabla": "Tabla",
    "Cymbal": "Cymbale",
    "Hi-hat": "Charleston",
    "Wood block": "Wood-block",
    "Tambourine": "Tambourin",
    "Rattle (instrument)": "Hochet",
    "Maraca": "Maracas",
    "Gong": "Gong",
    "Tubular bells": "Cloches tubulaires",
    "Mallet percussion": "Percussions à lames",
    "Marimba, xylophone": "Marimba, xylophone",
    "Glockenspiel": "Glockenspiel",
    "Vibraphone": "Vibraphone",
    "Steelpan": "Steelpan",
    "Orchestra": "Orchestre",
    "Brass instrument": "Cuivres",
    "French horn": "Cor",
    "Trumpet": "Trompette",
    "Trombone": "Trombone",
    "Bowed string instrument": "Cordes frottées",
    "String section": "Cordes",
    "Violin, fiddle": "Violon",
    "Pizzicato": "Pizzicato",
    "Cello": "Violoncelle",
    "Double bass": "Contrebasse",
    "Wind instrument, woodwind instrument": "Instrument à vent (bois)",
    "Flute": "Flûte",
    "Saxophone": "Saxophone",
    "Clarinet": "Clarinette",
    "Harp": "Harpe",
    "Bell": "Cloche",
    "Church bell": "Cloches d'église",
    "Jingle bell": "Grelots",
    "Bicycle bell": "Sonnette de vélo",
    "Tuning fork": "Diapason",
    "Chime": "Carillon",
    "Wind chime": "Carillon à vent",
    "Change ringing (campanology)": "Sonnerie de cloches",
    "Harmonica": "Harmonica",
    "Accordion": "Accordéon",
    "Bagpipes": "Cornemuse",
    "Didgeridoo": "Didgeridoo",
    "Shofar": "Shofar",
    "Theremin": "Thérémine",
    "Singing bowl": "Bol chantant",
    "Scratching (performance technique)": "Scratch (DJ)",
    "Pop music": "Pop",
    "Hip hop music": "Hip-hop",
    "Beatboxing": "Beatbox",
    "Rock music": "Rock",
    "Heavy metal": "Heavy metal",
    "Punk rock": "Punk rock",
    "Grunge": "Grunge",
    "Progressive rock": "Rock progressif",
    "Rock and roll": "Rock'n'roll",
    "Psychedelic rock": "Rock psychédélique",
    "Rhythm and blues": "Rhythm and blues",
    "Soul music": "Soul",
    "Reggae": "Reggae",
    "Country": "Country",
    "Swing music": "Swing",
    "Bluegrass": "Bluegrass",
    "Funk": "Funk",
    "Folk music": "Folk",
    "Middle Eastern music": "Musique orientale",
    "Jazz": "Jazz",
    "Disco": "Disco",
    "Classical music": "Musique classique",
    "Opera": "Opéra",
    "Electronic music": "Musique électronique",
    "House music": "House",
    "Techno": "Techno",
    "Dubstep": "Dubstep",
    "Drum and bass": "Drum and bass",
    "Electronica": "Electronica",
    "Electronic dance music": "Musique électro (EDM)",
    "Ambient music": "Ambient",
    "Trance music": "Trance",
    "Music of Latin America": "Musique latino-américaine",
    "Salsa music": "Salsa",
    "Flamenco": "Flamenco",
    "Blues": "Blues",
    "Music for children": "Musique pour enfants",
    "New-age music": "New age",
    "Vocal music": "Musique vocale",
    "A capella": "A cappella",
    "Music of Africa": "Musique africaine",
    "Afrobeat": "Afrobeat",
    "Christian music": "Musique chrétienne",
    "Gospel music": "Gospel",
    "Music of Asia": "Musique asiatique",
    "Carnatic music": "Musique carnatique",
    "Music of Bollywood": "Musique de Bollywood",
    "Ska": "Ska",
    "Traditional music": "Musique traditionnelle",
    "Independent music": "Musique indépendante",
    "Song": "Chanson",
    "Background music": "Musique de fond",
    "Theme music": "Thème musical",
    "Jingle (music)": "Jingle",
    "Soundtrack music": "Bande originale",
    "Lullaby": "Berceuse",
    "Video game music": "Musique de jeu vidéo",
    "Christmas music": "Musique de Noël",
    "Dance music": "Musique de danse",
    "Wedding music": "Musique de mariage",
    "Happy music": "Musique joyeuse",
    "Funny music": "Musique amusante",
    "Sad music": "Musique triste",
    "Tender music": "Musique douce",
    "Exciting music": "Musique entraînante",
    "Angry music": "Musique agressive",
    "Scary music": "Musique effrayante",
    "Wind": "Vent",
    "Rustling leaves": "Bruissement de feuilles",
    "Wind noise (microphone)": "Bruit de vent (micro)",
    "Thunderstorm": "Orage",
    "Thunder": "Tonnerre",
    "Water": "Eau",
    "Rain": "Pluie",
    "Raindrop": "Gouttes de pluie",
    "Rain on surface": "Pluie sur une surface",
    "Stream": "Ruisseau",
    "Waterfall": "Cascade",
    "Ocean": "Mer",
    "Waves, surf": "Vagues",
    "Steam": "Jet de vapeur",
    "Gurgling": "Gargouillis",
    "Fire": "Feu",
    "Crackle": "Crépitement",
    "Vehicle": "Véhicule",
    "Boat, Water vehicle": "Bateau",
    "Sailboat, sailing ship": "Voilier",
    "Rowboat, canoe, kayak": "Barque, canoë, kayak",
    "Motorboat, speedboat": "Bateau à moteur",
    "Ship": "Navire",
    "Motor vehicle (road)": "Véhicule à moteur",
    "Car": "Voiture",
    "Vehicle horn, car horn, honking": "Klaxon",
    "Toot": "Coup de klaxon",
    "Car alarm": "Alarme de voiture",
    "Power windows, electric windows": "Vitres électriques",
    "Skidding": "Dérapage",
    "Tire squeal": "Crissement de pneus",
    "Car passing by": "Voiture qui passe",
    "Race car, auto racing": "Course automobile",
    "Truck": "Camion",
    "Air brake": "Frein pneumatique",
    "Air horn, truck horn": "Klaxon de camion",
    "Reversing beeps": "Bips de recul",
    "Ice cream truck, ice cream van": "Camion de glaces",
    "Bus": "Bus",
    "Emergency vehicle": "Véhicule d'urgence",
    "Police car (siren)": "Sirène de police",
    "Ambulance (siren)": "Sirène d'ambulance",
    "Fire engine, fire truck (siren)": "Sirène de pompiers",
    "Motorcycle": "Moto",
    "Traffic noise, roadway noise": "Circulation",
    "Rail transport": "Chemin de fer",
    "Train": "Train",
    "Train whistle": "Sifflet de train",
    "Train horn": "Klaxon de train",
    "Railroad car, train wagon": "Wagon",
    "Train wheels squealing": "Crissement de roues de train",
    "Subway, metro, underground": "Métro",
    "Aircraft": "Aéronef",
    "Aircraft engine": "Moteur d'avion",
    "Jet engine": "Réacteur d'avion",
    "Propeller, airscrew": "Hélice",
    "Helicopter": "Hélicoptère",
    "Fixed-wing aircraft, airplane": "Avion",
    "Bicycle": "Vélo",
    "Skateboard": "Skateboard",
    "Engine": "Moteur",
    "Light engine (high frequency)": "Petit moteur (aigu)",
    "Dental drill, dentist's drill": "Fraise de dentiste",
    "Lawn mower": "Tondeuse",
    "Chainsaw": "Tronçonneuse",
    "Medium engine (mid frequency)": "Moteur moyen (médium)",
    "Heavy engine (low frequency)": "Gros moteur (grave)",
    "Engine knocking": "Cognement du moteur",
    "Engine starting": "Démarrage du moteur",
    "Idling": "Moteur au ralenti",
    "Accelerating, revving, vroom": "Accélération",
    "Door": "Porte",
    "Doorbell": "Sonnette",
    "Ding-dong": "Ding-dong",
    "Sliding door": "Porte coulissante",
    "Slam": "Claquement de porte",
    "Knock": "Coups frappés",
    "Tap": "Tapotement",
    "Squeak": "Couinement",
    "Cupboard open or close": "Porte de placard",
    "Drawer open or close": "Tiroir",
    "Dishes, pots, and pans": "Vaisselle",
    "Cutlery, silverware": "Couverts",
    "Chopping (food)": "Découpe d'aliments",
    "Frying (food)": "Friture",
    "Microwave oven": "Micro-ondes",
    "Blender": "Mixeur",
    "Water tap, faucet": "Robinet",
    "Sink (filling or washing)": "Évier",
    "Bathtub (filling or washing)": "Baignoire",
    "Hair dryer": "Sèche-cheveux",
    "Toilet flush": "Chasse d'eau",
    "Toothbrush": "Brosse à dents",
    "Electric toothbrush": "Brosse à dents électrique",
    "Vacuum cleaner": "Aspirateur",
    "Zipper (clothing)": "Fermeture éclair",
    "Keys jangling": "Clés",
    "Coin (dropping)": "Chute de pièce",
    "Scissors": "Ciseaux",
    "Electric shaver, electric razor": "Rasoir électrique",
    "Shuffling cards": "Mélange de cartes",
    "Typing": "Frappe au clavier",
    "Typewriter": "Machine à écrire",
    "Computer keyboard": "Clavier d'ordinateur",
    "Writing": "Écriture sur papier",
    "Alarm": "Alarme",
    "Telephone": "Téléphone",
    "Telephone bell ringing": "Sonnerie de téléphone",
    "Ringtone": "Sonnerie de portable",
    "Telephone dialing, DTMF": "Numérotation téléphonique",
    "Dial tone": "Tonalité",
    "Busy signal": "Tonalité occupée",
    "Alarm clock": "Réveil",
    "Siren": "Sirène",
    "Civil defense siren": "Sirène d'alerte",
    "Buzzer": "Buzzer",
    "Smoke detector, smoke alarm": "Détecteur de fumée",
    "Fire alarm": "Alarme incendie",
    "Foghorn": "Corne de brume",
    "Whistle": "Sifflet",
    "Steam whistle": "Sifflet à vapeur",
    "Mechanisms": "Mécanismes",
    "Ratchet, pawl": "Cliquet",
    "Clock": "Horloge",
    "Tick": "Tic d'horloge",
    "Tick-tock": "Tic-tac",
    "Gears": "Engrenages",
    "Pulleys": "Poulies",
    "Sewing machine": "Machine à coudre",
    "Mechanical fan": "Ventilateur",
    "Air conditioning": "Climatisation",
    "Cash register": "Caisse enregistreuse",
    "Printer": "Imprimante",
    "Camera": "Appareil photo",
    "Single-lens reflex camera": "Appareil photo reflex",
    "Tools": "Outils",
    "Hammer": "Marteau",
    "Jackhammer": "Marteau-piqueur",
    "Sawing": "Scie",
    "Filing (rasp)": "Limage (râpe)",
    "Sanding": "Ponçage",
    "Power tool": "Outil électrique",
    "Drill": "Perceuse",
    "Explosion": "Explosion",
    "Gunshot, gunfire": "Coups de feu",
    "Machine gun": "Mitrailleuse",
    "Fusillade": "Fusillade",
    "Artillery fire": "Tirs d'artillerie",
    "Cap gun": "Pistolet à amorces",
    "Fireworks": "Feux d'artifice",
    "Firecracker": "Pétards",
    "Burst, pop": "Éclatement",
    "Eruption": "Éruption volcanique",
    "Boom": "Détonation sourde",
    "Wood": "Bruit de bois",
    "Chop": "Coup de hache",
    "Splinter": "Éclats de bois",
    "Crack": "Craquement sec",
    "Glass": "Verre",
    "Chink, clink": "Tintement de verre",
    "Shatter": "Bris de verre",
    "Liquid": "Liquide",
    "Splash, splatter": "Éclaboussures",
    "Slosh": "Clapotis",
    "Squish": "Bruit spongieux",
    "Drip": "Goutte à goutte",
    "Pour": "Eau versée",
    "Trickle, dribble": "Filet d'eau",
    "Gush": "Jaillissement",
    "Fill (with liquid)": "Remplissage",
    "Spray": "Pulvérisation",
    "Pump (liquid)": "Pompage (liquide)",
    "Stir": "Mélange à la cuillère",
    "Boiling": "Ébullition",
    "Sonar": "Sonar (son électronique)",
    "Arrow": "Flèche",
    "Whoosh, swoosh, swish": "Souffle rapide (whoosh)",
    "Thump, thud": "Bruit sourd",
    "Thunk": "Choc sourd",
    "Electronic tuner": "Accordeur électronique",
    "Effects unit": "Processeur d'effets",
    "Chorus effect": "Effet chorus",
    "Basketball bounce": "Rebond de ballon de basket",
    "Bang": "Choc violent",
    "Slap, smack": "Claque",
    "Whack, thwack": "Coup sec",
    "Smash, crash": "Fracas",
    "Breaking": "Bruit de casse",
    "Bouncing": "Rebonds",
    "Whip": "Coup de fouet",
    "Flap": "Battement (drapeau, voile)",
    "Scratch": "Grattement",
    "Scrape": "Raclement",
    "Rub": "Frottement",
    "Roll": "Roulement",
    "Crushing": "Écrasement",
    "Crumpling, crinkling": "Froissement",
    "Tearing": "Déchirement",
    "Beep, bleep": "Bip",
    "Ping": "Ping",
    "Ding": "Ding",
    "Clang": "Choc métallique",
    "Squeal": "Crissement",
    "Creak": "Grincement",
    "Rustle": "Bruissement",
    "Whir": "Ronronnement mécanique",
    "Clatter": "Entrechoquement",
    "Sizzle": "Grésillement",
    "Clicking": "Clics",
    "Clickety-clack": "Claquements rythmés",
    "Rumble": "Grondement",
    "Plop": "Plouf",
    "Jingle, tinkle": "Tintement",
    "Hum": "Bourdonnement grave",
    "Zing": "Sifflement bref",
    "Boing": "Boing (ressort)",
    "Crunch": "Craquement",
    "Silence": "Silence",
    "Sine wave": "Onde sinusoïdale",
    "Harmonic": "Harmonique",
    "Chirp tone": "Balayage de fréquence",
    "Sound effect": "Effet sonore",
    "Pulse": "Impulsion",
    "Inside, small room": "Intérieur, petite pièce",
    "Inside, large room or hall": "Intérieur, grande salle",
    "Inside, public space": "Intérieur, lieu public",
    "Outside, urban or manmade": "Extérieur, ville",
    "Outside, rural or natural": "Extérieur, campagne",
    "Reverberation": "Réverbération",
    "Echo": "Écho",
    "Noise": "Bruit",
    "Environmental noise": "Bruit ambiant",
    "Static": "Parasites",
    "Mains hum": "Ronflement secteur",
    "Distortion": "Distorsion",
    "Sidetone": "Retour de voix (téléphone)",
    "Cacophony": "Cacophonie",
    "White noise": "Bruit blanc",
    "Pink noise": "Bruit rose",
    "Throbbing": "Pulsation",
    "Vibration": "Vibration",
    "Television": "Télévision",
    "Radio": "Radio",
    "Field recording": "Enregistrement de terrain",
}
